spring:
  application:
    name: Bunge

##db connection(MySQL)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(BiouDVkWy0mTZp+tYT4buEA6yKH1+w9Nmy83Gb7Uq7ww36o5997Y45R3EUzc71cL9bFRWJaZV6it/iVPtYFNXS6ZeOgqSQIZKi6RPLl1pYMv4Yb4i/0o6rzuu0hN+kEGvDfFr5XtyLuM/ihjKupdXA==)
    username: ENC(z2ZTll4++Fd3NI6qurr/+g==)
    password: ENC(Vw2XZ103MqOMv7kcXFt/Evp9k1EG34Ii)

##aws path
review:
  savefolder: /home/ubuntu/download/review-upload

jasypt:
  encryptor:
    bean: jasyptStringEncryptor