spring:
  application:
    name: Bunge

##db connection(MySQL)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(OJwYjj9ZefFyQmDHDoHH3PbGgG16MEPb8btmytEsqHHBmzdijnHyJvM79/5ikxz4MYrHCqAtXONA9Chzipru1HKU8ecwXHeELMEdhjNHsAW/ZYE7TuhPBsl6LWGXdtXrNqsBdnuVTftkdIuVbwB71A==)
    username: ENC(z2ZTll4++Fd3NI6qurr/+g==)
    password: ENC(Vw2XZ103MqOMv7kcXFt/Evp9k1EG34Ii)


##aws path
review:
  savefolder: /home/ubuntu/download/review-upload

jasypt:
  encryptor:
    bean: jasyptStringEncryptor